#!/usr/bin/env python3
"""
sync-plates.py — propagate canonical decode-state entries from
/satellite/.processed-iq-canonical.json into
/website/apps/gs/src/content/plates.json, copy any decoded PNGs
into /website/apps/gs/public/plates/, and optionally rebuild +
deploy the gs Pages project.

The canonical file is generated by build-canonical.py from the
append-only NDJSON. Reading canonical guarantees 1 IQ : 1 plate.

Idempotent. No LLM. Designed to be run unattended on a systemd
timer (or after every decode).

Match strategy — a canonical entry is considered "already on file" if:
  1. its sha256_first_mb matches an existing plates.json entry, OR
  2. its (normalised satellite, captured_at within a per-band
     tolerance window) matches one.

The (sat, time) fallback covers the hand-curated bootstrap entries
that don't carry sha256s.

Hand-curated entries are never modified. The script only APPENDS
new entries; it does not enrich, rename, or rewrite existing ones.

Usage:
  ./sync-plates.py              # update plates.json + copy PNGs, no deploy
  ./sync-plates.py --deploy     # also: pnpm build:gs + wrangler deploy
  ./sync-plates.py --dry-run    # report what would change, write nothing
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ──────────────────────────────────────────────────────────────────
# Paths

CANONICAL     = Path("/satellite/.processed-iq-canonical.json")
NDJSON        = Path("/satellite/.processed-iq-log.ndjson")  # fallback
PLATES_JSON   = Path("/website/apps/gs/src/content/plates.json")
PUBLIC_PLATES = Path("/website/apps/gs/public/plates")
IMAGES_ROOT   = Path("/satellite/images")
PASSES_ROOT   = Path("/satellite/passes")
WEBSITE_ROOT  = Path("/website")

CF_TOKEN_PATH = Path.home() / ".config" / "nl06" / "cloudflare.token"
CF_ACCOUNT_ID = "412810aff4761352d5c33b9257311f20"
CF_PROJECT    = "nl06-gs"

# ──────────────────────────────────────────────────────────────────
# Satellite → display name, band, default L-band frequency

SAT_INFO: dict[str, dict[str, Any]] = {
    "m2-3":       {"display": "METEOR-M N2-3", "band": "VHF", "freq": 137.900},
    "m2-4":       {"display": "METEOR-M N2-4", "band": "VHF", "freq": 137.900},
    "gk-2a":      {"display": "GEO-KOMPSAT-2A", "band": "L",   "freq": 1692.140},
    "elektro-l3": {"display": "ELEKTRO-L3",    "band": "L",   "freq": 1691.000},
    "elektro-l5": {"display": "ELEKTRO-L5",    "band": "L",   "freq": 1691.000},
    "fengyun-2h": {"display": "FENGYUN-2H",    "band": "L",   "freq": 1687.500},
}

# Normalise NDJSON satellite keys to a single canonical form for matching
# against plates.json's display field.
DISPLAY_TO_KEY = {v["display"]: k for k, v in SAT_INFO.items()}

# ──────────────────────────────────────────────────────────────────
# Helpers

def parse_iso(s: str) -> datetime | None:
    """Parse an ISO timestamp, returning a UTC datetime or None."""
    if not s:
        return None
    try:
        # python's fromisoformat handles +05:30 since 3.11; older
        # versions need the trailing Z normalised.
        dt = datetime.fromisoformat(s.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except ValueError:
        return None

def sat_key(plate_or_entry: dict) -> str | None:
    """Reverse-map an NDJSON 'satellite' or a plate 'satellite' display
    string to the SAT_INFO key. Returns None if unknown."""
    s = plate_or_entry.get("satellite", "")
    if s in SAT_INFO:
        return s
    return DISPLAY_TO_KEY.get(s)

def fingerprint(entry: dict) -> tuple[str | None, str | None]:
    """(sha, satellite-key + UTC minute) for idempotent matching."""
    sha = entry.get("iq_sha256_first_mb") or entry.get("sha256_first_mb")
    k = sat_key(entry)
    dt = parse_iso(entry.get("captured_at") or entry.get("aos_iso") or entry.get("pi_mtime_iso") or "")
    if k and dt:
        # Round to the nearest minute. ±60 seconds tolerance via lookup.
        time_key = dt.strftime("%Y%m%dT%H%M")
        return sha, f"{k}@{time_key}"
    return sha, None

def derive_id(entry: dict) -> str:
    """Stable id for a new plate from filename + AOS timestamp."""
    fname = entry.get("pi_filename", "unknown.iq")
    stem = re.sub(r"\.iq$", "", fname)
    aos = entry.get("aos_iso") or entry.get("pi_mtime_iso") or ""
    dt = parse_iso(aos)
    ts = dt.strftime("%Y%m%dT%H%MZ") if dt else "00000000T0000Z"
    skey = entry["satellite"].replace("-", "")
    raw = f"{skey}-{ts}-{stem}"
    safe = re.sub(r"[^A-Za-z0-9._-]", "-", raw)
    return safe[:120]

def channel_from_filename(name: str) -> str | None:
    if "IR105" in name: return "IR105 (10.3 μm)"
    if "MSU-MR-1" in name or "msu_mr_1" in name.lower(): return "MSU-MR ch.1 (0.5–0.7 μm)"
    if "MSU-MR-2" in name or "msu_mr_2" in name.lower(): return "MSU-MR ch.2 (0.7–1.1 μm)"
    if "MSU-MR-3" in name or "msu_mr_3" in name.lower(): return "MSU-MR ch.3 (3.5–4.1 μm)"
    return None

def is_colorised(name: str) -> bool:
    n = name.lower()
    return any(k in n for k in ("sanchez", "redblue", "red_blue", "purple_yellow"))

def find_image_for(entry: dict) -> Path | None:
    """Best-effort search for a decoded PNG matching one NDJSON entry."""
    skey = entry.get("satellite", "")
    aos = entry.get("aos_iso") or entry.get("pi_mtime_iso") or ""
    dt = parse_iso(aos)
    if not dt:
        return None
    ts_utc_compact = dt.strftime("%Y%m%dT%H%M")  # 12 chars, minute resolution

    candidates: list[Path] = []

    # GK-2A imagery lives under /satellite/images/gk-2a/{sanchez,raw}/
    if skey == "gk-2a":
        for variant in ("sanchez", "raw"):
            d = IMAGES_ROOT / "gk-2a" / variant
            if d.exists():
                for png in sorted(d.glob("*.png")):
                    if ts_utc_compact in png.name:
                        candidates.append(png)

    # METEOR decoded products live under /satellite/images/meteor-<sat>/<date>/
    if skey.startswith("m2-"):
        date_part = dt.strftime("%Y-%m-%d")
        for d in IMAGES_ROOT.glob(f"meteor-{skey}/*"):
            if d.is_dir() and date_part in d.name:
                msu = d / "MSU-MR-1.png"
                if msu.exists():
                    candidates.append(msu)

    # Fall back: scan the documented nas_pass_dir, and also the new
    # /satellite/passes/ mirror, for any decoded-looking PNG.
    pass_dir = entry.get("nas_pass_dir", "")
    if pass_dir:
        candidates_dirs = [Path(pass_dir)]
        # If old layout, also check the new /satellite/passes/ path.
        m = re.match(r"^/satellite/(meteor-m2-[34]|gk-2a|elektro-l[35]|fengyun-2h)/(.+)$", pass_dir)
        if m:
            candidates_dirs.append(PASSES_ROOT / m.group(1) / m.group(2))
        for d in candidates_dirs:
            if d.exists() and d.is_dir():
                for png in sorted(d.glob("*.png")):
                    n = png.name.lower()
                    if any(skip in n for skip in ("comparison", "constellation", "iqdump", "spectrum")):
                        continue
                    candidates.append(png)

    return candidates[0] if candidates else None

def nd_to_plate(entry: dict, copy_images: bool = True) -> dict:
    """Translate one canonical (or NDJSON) record to a plates.json record.
    Set copy_images=False to skip the side-effect filesystem copy — used
    by --dry-run."""
    skey = entry["satellite"]
    info = SAT_INFO.get(skey, {"display": skey.upper(), "band": "L", "freq": 0.0})

    aos = entry.get("aos_iso") or entry.get("pi_mtime_iso") or ""
    dt = parse_iso(aos) or datetime.now(timezone.utc)

    plate: dict[str, Any] = {
        "id": derive_id(entry),
        "satellite": info["display"],
        "captured_at": dt.isoformat().replace("+00:00", "Z"),
        "band": info["band"],
        "frequency_mhz": info["freq"],
        "outcome": entry["decode_outcome"],
        "cadu_bytes": entry.get("cadu_bytes", 0),
        "iq_sha256_first_mb": entry.get("sha256_first_mb"),
        "draft": False,
    }

    # Polar passes carry an AOS we know; GEO is continuous.
    if skey.startswith("m2-"):
        plate["aos"] = dt.isoformat().replace("+00:00", "Z")

    if entry.get("notes"):
        plate["notes"] = entry["notes"]

    # Image discovery — only for outcomes that could have produced one.
    if entry["decode_outcome"] in ("success", "partial"):
        img = find_image_for(entry)
        if img:
            safe_name = re.sub(r"[^a-zA-Z0-9._-]", "-", f"{plate['id']}-{img.name}")[:200]
            if copy_images:
                dst = PUBLIC_PLATES / safe_name
                if not dst.exists():
                    PUBLIC_PLATES.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(img, dst)
            plate["image"] = f"/plates/{safe_name}"
            plate["title"] = f"{info['display']} · auto-ingested"
            ch = channel_from_filename(img.name)
            if ch:
                plate["channel"] = ch
            plate["colorised"] = is_colorised(img.name)
            plate["pipeline"] = "SatDump · auto-ingested from canonical.json"

    return plate

# ──────────────────────────────────────────────────────────────────
# Main

def load_canonical() -> list[dict]:
    """Prefer canonical.json (1 entry per IQ). Fall back to NDJSON if
    canonical doesn't exist yet — but warn loudly, because that path
    cannot guarantee 1:1."""
    if CANONICAL.exists():
        with CANONICAL.open(encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            sys.exit("sync-plates: canonical.json is not a JSON array.")
        return data

    print(f"sync-plates: WARNING — canonical not found at {CANONICAL}. "
          f"Falling back to NDJSON; duplicate IQ entries are possible. "
          f"Run build-canonical.py to fix.", file=sys.stderr)
    if not NDJSON.exists():
        sys.exit(f"sync-plates: NDJSON also not found: {NDJSON}")
    out: list[dict] = []
    with NDJSON.open(encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f"sync-plates: warning: malformed NDJSON line {n}: {e}", file=sys.stderr)
    return out

def load_existing() -> list[dict]:
    if not PLATES_JSON.exists():
        return []
    with PLATES_JSON.open(encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        sys.exit("sync-plates: plates.json is not a JSON array; bailing.")
    return data

def index_existing(entries: list[dict]) -> tuple[set[str], set[str]]:
    """Return (sha256 set, fingerprint set) of already-known entries,
    where the fingerprint set is expanded across a per-band tolerance
    window: ±10 minutes for L-band GEO captures, ±2 minutes for VHF
    polar passes. GEO needs the wider window because NDJSON records
    capture-start time while plates.json carries the satellite frame
    timestamp (typically minutes later)."""
    from datetime import timedelta
    shas: set[str] = set()
    keys: set[str] = set()
    for e in entries:
        sha, key = fingerprint(e)
        if sha:
            shas.add(sha)
        if not key:
            continue
        k, ts = key.split("@")
        dt = datetime.strptime(ts, "%Y%m%dT%H%M").replace(tzinfo=timezone.utc)
        band = SAT_INFO.get(k, {}).get("band", "L")
        window_min = 10 if band == "L" else 2
        for delta_min in range(-window_min, window_min + 1):
            shifted = dt + timedelta(minutes=delta_min)
            keys.add(f"{k}@{shifted.strftime('%Y%m%dT%H%M')}")
    return shas, keys

def deploy_gs() -> int:
    """pnpm build + wrangler deploy. Returns process exit code."""
    print("sync-plates: building apps/gs ...")
    r = subprocess.run(
        ["pnpm", "--filter", "@nl06/gs", "build"],
        cwd=WEBSITE_ROOT,
    )
    if r.returncode != 0:
        print("sync-plates: build failed", file=sys.stderr)
        return r.returncode

    if not CF_TOKEN_PATH.exists():
        print(f"sync-plates: CF token not found at {CF_TOKEN_PATH}; skipping deploy.", file=sys.stderr)
        return 2

    print("sync-plates: deploying nl06-gs ...")
    env = os.environ.copy()
    env["CLOUDFLARE_API_TOKEN"] = CF_TOKEN_PATH.read_text().strip()
    env["CLOUDFLARE_ACCOUNT_ID"] = CF_ACCOUNT_ID
    r = subprocess.run(
        [
            "pnpm", "dlx", "wrangler", "pages", "deploy",
            "apps/gs/dist",
            f"--project-name={CF_PROJECT}",
            "--branch=main",
            "--commit-dirty=true",
        ],
        cwd=WEBSITE_ROOT, env=env,
    )
    return r.returncode

def main(argv: list[str]) -> int:
    dry_run = "--dry-run" in argv
    do_deploy = "--deploy" in argv

    nd_entries = load_canonical()
    existing = load_existing()
    shas, keys = index_existing(existing)

    added: list[dict] = []
    for entry in nd_entries:
        sha = entry.get("sha256_first_mb")
        _, time_key = fingerprint(entry)
        if sha and sha in shas:
            continue
        if time_key and time_key in keys:
            continue
        plate = nd_to_plate(entry, copy_images=not dry_run)
        added.append(plate)
        if sha:
            shas.add(sha)
        if time_key:
            keys.add(time_key)

    if not added:
        print(f"sync-plates: source has {len(nd_entries)} canonical IQ records; "
              f"plates.json has {len(existing)}; nothing new.")
        if do_deploy and not dry_run:
            # Optional: still redeploy in case unrelated code changed.
            # Default: do nothing.
            print("sync-plates: --deploy set but no changes; skipping rebuild.")
        return 0

    print(f"sync-plates: source has {len(nd_entries)} canonical IQ records; "
          f"plates.json has {len(existing)}; adding {len(added)} new entries:")
    for p in added:
        marker = "IMG" if p.get("image") else "log"
        print(f"  [{marker}] {p['id']:60}  {p['captured_at']}  {p['outcome']:14}")

    if dry_run:
        print("sync-plates: --dry-run; not writing, no images copied.")
        return 0

    merged = existing + added
    # Sort descending by captured_at for editorial readability of the file.
    merged.sort(key=lambda e: e["captured_at"], reverse=True)
    with PLATES_JSON.open("w", encoding="utf-8") as f:
        json.dump(merged, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"sync-plates: wrote {PLATES_JSON} ({len(merged)} entries).")

    if do_deploy:
        rc = deploy_gs()
        if rc != 0:
            return rc

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
